# Generated by Django 3.2.14 on 2022-07-20 05:11

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('channel', models.CharField(choices=[('Android', 'Android'), ('ios', 'Ios'), ('Web', 'Web')], max_length=10, verbose_name='channel')),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=4, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(default=datetime.datetime(2022, 7, 20, 5, 13, 39, 969391, tzinfo=utc))),
                ('receipt_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'One Time Password',
                'verbose_name_plural': 'One Time Passwords',
            },
        ),
    ]
