# Generated by Django 3.2.14 on 2022-07-20 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_otprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 10, 5, 48, 762326, tzinfo=utc)),
        ),
    ]
